// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type DeleteUserResponse struct {
	DeleteUserID int `json:"deleteUserId"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type User struct {
	ID    int    `json:"id" gorm:"primaryKey;autoIncrement"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
